config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|ja/ do
    root 'static_pages#home'

    # static_pages
    get '/guest', to:'static_pages#guest'
    get '/terms', to:'static_pages#terms'
    get '/privacy', to:'static_pages#privacy'

    # users
    get '/signup', to:'users#new'
    post '/guest', to:'users#create_guest'
    resources :users, only: [:new, :create, :edit, :update, :destroy]

    # sessions
    get     '/login', to:'sessions#new'
    post   '/login', to:'sessions#create'
    delete '/logout', to:'sessions#destroy'

    # account_activations
    resources :account_activations, only: [:edit]

    # password_resets
    resources :password_resets, only: [:new, :create, :edit, :update]

    # contacts
    resources :contacts, only: [:new, :create]

    # link_groups
    resources :link_groups, only: [:show, :create, :update, :destroy]

    # links
    resources :links, only: [:create, :update, :destroy]
    get '/search', to:'links#search'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @link_group  = current_user.link_groups.build
      @link_groups = current_user.link_groups.all
      @link = current_user.links.build
      @links = current_user.links.all
    end
  end

  def guest
    # 現在のユーザーが「nilである」または「guestではない」=> ルートにリダイレクト
    redirect_to root_url if !current_user || !current_user.guest?
    if logged_in?
      @link_group  = current_user.link_groups.build
      @link_groups = current_user.link_groups.all
      @link = current_user.links.build
      @links = current_user.links.all
    end
  end

  def about
  end

  def terms
  end

  def privacy
  end
end

app/views/static_pages/_add_group.html.erb
<%= form_with(model: @link_group, local: false, id: "add-group") do |f| %>
  <div class="title"><%= t "dictionary.common.new_group" %></div>
  <%= f.text_field :name, placeholder: t("dictionary.common.group_name"), class: "hidden" %>
  <%= f.submit t("dictionary.common.create"), class: "button hidden" %>
<% end %>

app/views/static_pages/_add_link.html.erb
<%= form_with(model: @link, local: false, id: "add-link", class: "hidden") do |f| %>
  <div class="title"><%= t "dictionary.common.new_link" %></div>
  <%= f.text_field :title, placeholder: t("dictionary.common.link_title"), class: "hidden" %>
  <%= f.text_field :url, placeholder: "URL", class: "hidden" %>
  <%= f.hidden_field :link_group_id %>
  <%= f.submit t("dictionary.common.create"), class: "button hidden" %>
<% end %>

app/views/static_pages/_edit_group_modal.html.erb
<%= form_with(scope: :link_group, method: :patch,
                                                    local: false,
                                                    class: "hidden",
                                                    id: "edit-group-modal") do |f| %>
  <div class="group-header">
    <%= f.text_field :name  %>
    <%= f.submit t("dictionary.common.update"), class: "button hidden" %>
    <%= link_to "", class: "delete-icon",
          method: :delete,
          data: { confirm:  t("dictionary.delete_group.message"), remote: true} do %>
      <span class="material-icons" style="font-size: 20px;">delete_outline</span>
    <% end %>
  </div>
<% end %>

app/views/static_pages/_edit_link_modal.html.erb
<%= form_with(scope: :link, method: :patch,
                                          local: false,
                                          class: "hidden",
                                          id: "edit-link-modal") do |f| %>
  <div class="link-header">
    <%= f.text_field :title %>
    <%= f.submit t("dictionary.common.update"), class: "button hidden" %>
    <%= link_to "", class: "delete-icon",
                        method: :delete,
                        data: { confirm:  t("dictionary.delete_link.message"), remote: true} do %>
      <span class="material-icons" style="font-size: 20px;">delete_outline</span>
    <% end %>
  </div>
  <div class="link-url">
    <%= f.text_field :url %>
  </div>
<% end %>

app/views/static_pages/_footer.html.erb
<footer>
    <ul class="footer-menu">
      <li><%= link_to t("dictionary.footer.home"), root_path %></li>
      <li><%= link_to t("dictionary.footer.contact"), new_contact_path %></li>
      <li><%= link_to t("dictionary.footer.terms"), terms_path %></li>
      <li><%= link_to t("dictionary.footer.privacy"), privacy_path %></li>
    </ul>
    <p class="copyright">&copy; Daichi Hayasaka All Rights Reserved.</p>
  </footer>

app/views/static_pages/_home_logged_in.html.erb
<div class="home-container">
  <div id="mask-modal" class="hidden"></div>

  <div class="header-outer">
    <header class="home-header">
      <div class="humbugger">
        <span class="material-icons" id="open-mobile-menu">menu</span>
      </div>
      <div class="logo">
        <%= link_to image_tag("5keeps.png", alt: "logo"), root_path %>
      </div>
      <%= render 'static_pages/search_form' %>
      <div class="account header">
        <div class="account-inner-container">
          <span class="material-icons" id="account-icon">account_circle</span>
          <span class="user-name"><%= current_user.name %></span>
          <span class="material-icons" id="dropdown-icon">arrow_drop_down</span>
          <ul class="dropdown-list">
            <li><%= link_to t('static_pages.home.settings'), edit_user_path(current_user) %></li>
            <li><%= link_to t('static_pages.home.logout'), logout_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </header>
  </div class="header-outer">

  <main class="home-main">
    <%= render 'static_pages/home_menu_mobile' %>
    <%= render 'static_pages/home_menu_desktop' %>
    <%= render 'static_pages/edit_group_modal' %>
    <%= render 'static_pages/edit_link_modal' %>
    <section class="home-content">
      <%= render 'static_pages/add_group' %>
      <%= render 'static_pages/add_link' %>      
      <ul class="link">
        <% if current_user.links.any? %>
          <%= render @links %>
        <% end %>
      </ul>
    </section>
    <div id="mask-mobile-menu" class="hidden">
      <span class="material-icons" id="close-mobile-menu">close</span>
    </div>
  </main>

  <%= render 'static_pages/footer' %>
</div><!-- /.home-container -->
<%= javascript_pack_tag 'custom/home' %>

app/views/static_pages/_home_menu_desktop.html.erb
<section class="menu desktop">
  <nav>
    <ul class="menu-list">
      <li class="active home">
        <span class="material-icons">home</span>
        <%= link_to t("static_pages.home.menu.home"),  root_path, data: { remote: true} %>
      </li>
      <% if current_user.link_groups.any? %>
        <%= render @link_groups %>
      <% end %>
    </ul>
  </nav>
</section><!-- /.menu.desktop -->

app/views/static_pages/_home_menu_mobile.html.erb
<section class="menu mobile">
  <header class="menu-header">
    <div class="logo">
      <%= link_to image_tag("5keeps.png", alt: "logo"), root_path %>
    </div>
    <% if current_user.guest? %>
      <div class="links-guest">
        <div class="account">
          <span class="material-icons" id="account-icon">account_circle</span>
          <span class="user-name"><%= t "static_pages.guest.guest" %></span>
        </div>
        <%= link_to t("dictionary.common.signup"), signup_path, class: "button" %>
      </div>
    <% else %>
      <div class="account">
        <span class="material-icons" id="account-icon">account_circle</span>
        <span class="user-name"><%= current_user.name %></span>
        <span class="material-icons" id="dropdown-icon">arrow_drop_down</span>
        <ul class="dropdown-list">
          <li><%= link_to t('static_pages.home.settings'), edit_user_path(current_user) %></li>
          <li><%= link_to t('static_pages.home.logout'), logout_path, method: :delete %></li>
        </ul>
      </div>
    <% end %>
  </header>
  <nav>
    <ul class="menu-list">
      <li class="active home">
        <span class="material-icons">home</span>
        <%= link_to t("static_pages.home.menu.home"),  root_path, data: { remote: true} %>
      </li>
      <% if current_user.link_groups.any? %>
        <%= render @link_groups %>
      <% end %>
    </ul>
  </nav>
</section><!-- /.menu.mobile -->

app/views/static_pages/_home_not_logged_in.en.html.erb
<div class="index-container">
  <div class="header-outer">
    <header class="index-header">
      <div class="logo">
        <%= link_to image_tag("5keeps.png", alt: "logo"), root_path %>
      </div>
      <div class="index-links">
        <div class="language">
          <span><%= t "static_pages.home.language" %></span>
          <span class="material-icons" id="dropdown-icon">arrow_drop_down</span>
          <ul class="dropdown-list">
            <li><%= link_to "English", root_path(locale: :en) %></li>
            <li><%= link_to "日本語", root_path(locale: :ja) %></li>
          </ul>
        </div>
        <div class="login">
          <span class="material-icons">person_outline</span>
          <%= link_to t("dictionary.common.login"), login_path %>
        </div>
        <%= link_to t("dictionary.common.signup"), signup_path, class: "button" %>
      </div>
    </header>
  </div>

  <main class="index-main">
    <section class="index-content top">
      <h1>Fast access to<br>
              what you need Now
      </h1>
      <p class="sub-title">The world's simplest bookmark application</p>
      <%= link_to "Free Trial", guest_path, method: :post, class: "button" %>
    </section>
    
    <section class="index-content how-to-use">
      <h2>How to use</h2>
      <p>
          You can create up to 5 groups and 5 links per group.
          By keeping only the information you need now, you can quickly access to it.<br>
          You can access to trial page from「Free Trial」button.
          Once you signup to 5Keeps, the groups and links you created can be saved to your account.
      </p>

      <div class="carousel mobile">
        <div class="slides">
          <ul>
            <li>
              <div class="title">1. Create Groups</div>
              <div class="container">
                <%= image_tag("about_mb_01_en.png", alt: "Screenshot for create groups") %>
              </div>
              <p>You can create up to 5 groups</p>
            </li>
            <li>
              <div class="title">2. Select a group</div>
              <div class="container">
                <%= image_tag("about_mb_02_en.png", alt: "Screenshot for select a group") %>
              </div>
              <p>Select the group you want to create links.</p>
            </li>
            <li>
              <div class="title">3. Create links</div>
              <div class="container">
                <%= image_tag("about_mb_03_en.png", alt: "Screenshot for create links") %>
              </div>
              <p>You can create up to 5 links for each group.</p>
            </li>
          </ul>
        </div>

        <button class="prev">
          <span class="material-icons">arrow_back_ios</span>
        </button>
        <button class="next">
          <span class="material-icons">arrow_forward_ios</span>              
        </button>
        
        <nav>
        </nav>                  
      </div>

      <div class="carousel desktop">
        <div class="slides">
          <ul>
            <li>
              <div class="title">1. Create Groups</div>
              <div class="container">
                <%= image_tag("about_pc_01_en.png", alt: "Screenshot for create groups") %>
              </div>
              <p>You can create up to 5 groups</p>
            </li>

            <li>
              <div class="title">2. Select a group</div>
              <div class="container">
                <%= image_tag("about_pc_02_en.png", alt: "Screenshot for select a group") %>
              </div>
              <p>Select the group you want to create links.</p>
            </li> 

            <li>
              <div class="title">3. Create links</div>
              <div class="container">
                <%= image_tag("about_pc_03_en.png", alt: "Screenshot for create links") %>
              </div>
              <p>You can create up to 5 links for each group.</p>
            </li>              
          </ul>
        </div>

        <button class="prev">
          <span class="material-icons">arrow_back_ios</span>
        </button>
        <button class="next">
          <span class="material-icons">arrow_forward_ios</span>              
        </button>

        <nav>
        </nav>             
      </div>
    </section>
  </main>
  <%= render 'static_pages/footer' %>
</div>
<%= javascript_pack_tag 'custom/home_not_logged_in' %>

app/views/static_pages/_home_not_logged_in.ja.html.erb
<div class="index-container">
  <div class="header-outer">
    <header class="index-header">
      <div class="logo">
        <%= link_to image_tag("5keeps.png", alt: "logo"), root_path %>
      </div>
      <div class="index-links">
        <div class="language">
          <span><%= t "static_pages.home.language" %></span>
          <span class="material-icons" id="dropdown-icon">arrow_drop_down</span>
          <ul class="dropdown-list">
            <li><%= link_to "English", root_path(locale: :en) %></li>
            <li><%= link_to "日本語", root_path(locale: :ja) %></li>
          </ul>
        </div>
        <div class="login">
          <span class="material-icons">person_outline</span>
          <%= link_to t("dictionary.common.login"), login_path %>
        </div>
        <%= link_to t("dictionary.common.signup"), signup_path, class: "button" %>
      </div>
    </header>
  </div>

  <main class="index-main">
    <section class="index-content top">
      <h1>必要な情報を<br>
            「サッと」呼び出す
      </h1>
      <p class="sub-title">シンプルを追求した、ブックマークアプリ</p>
      <%= link_to "まずはお試し", guest_path, method: :post, class: "button" %>
    </section>
    
    <section class="index-content how-to-use">
      <h2>使い方</h2>
      <p>
          グループを5つまで作成でき、リンクをグループ毎に5つまで作成できます。
          「今」必要な情報だけを保存することで、いつでも「サッと」呼び出せます。<br>
        「まずはお試し」ボタンから、お試し用のページに移動できます。
          無料の会員登録をして頂くと、作成したグループとリンクを保存できます。
      </p>

      <div class="carousel mobile">
        <div class="slides">
          <ul>
            <li>
              <div class="title">1. グループを作成</div>
              <div class="container">
                <%= image_tag("about_mb_01_ja.png", alt: "グループ作成のスクリーンショット") %>
              </div>
              <p>グループを5つまで作成できます。</p>
            </li>
            <li>
              <div class="title">2. グループを選択</div>
              <div class="container">
                <%= image_tag("about_mb_02_ja.png", alt: "グループ選択のスクリーンショット") %>
              </div>
              <p>リンクを作成するグループを選択します。</p>
            </li>
            <li>
              <div class="title">3. リンクを作成</div>
              <div class="container">
                <%= image_tag("about_mb_03_ja.png", alt: "リンク作成のスクリーンショット") %>
              </div>
              <p>リンクをグループ毎に5つまで作成できます。</p>
            </li>
          </ul>
        </div>
        
        <button class="prev">
          <span class="material-icons">arrow_back_ios</span>
        </button>
        <button class="next">
          <span class="material-icons">arrow_forward_ios</span>              
        </button>

        <nav>
        </nav>                   
      </div>

      <div class="carousel desktop">
        <div class="slides">
          <ul>
            <li>
              <div class="title">1. グループを作成</div>
              <div class="container">
                <%= image_tag("about_pc_01_ja.png", alt: "グループ作成のスクリーンショット") %>
              </div>
              <p>グループを5つまで作成できます。</p>
            </li>
            <li>
              <div class="title">2. グループを選択</div>
              <div class="container">
                <%= image_tag("about_pc_02_ja.png", alt: "グループ選択のスクリーンショット") %>
              </div>
              <p>リンクを作成するグループを選択します。</p>
            </li>
            <li>
              <div class="title">3. リンクを作成</div>
              <div class="container">
                <%= image_tag("about_pc_03_ja.png", alt: "リンク作成のスクリーンショット") %>
              </div>
              <p>リンクをグループ毎に5つまで作成できます。</p>
            </li>
          </ul>
        </div>
        
        <button class="prev">
          <span class="material-icons">arrow_back_ios</span>
        </button>
        <button class="next">
          <span class="material-icons">arrow_forward_ios</span>              
        </button>

        <nav>
        </nav>                   
      </div>
    </section>
  </main>
  <%= render 'static_pages/footer' %>
</div>
<%= javascript_pack_tag 'custom/home_not_logged_in' %>

app/views/static_pages/_search_form.html.erb
<%= form_with url: search_path, method: :get, local: false, class: "search-form" do |f| %>
  <div class="search-icon">
    <span class="material-icons" id="search">search</span>
  </div>
  <%= f.text_field :title, placeholder: t("dictionary.common.search") %>
  <%= f.submit "", style: "display: none" %>
<% end %>

app/views/static_pages/guest.html.erb
<div class="home-container">
  <div id="mask-modal" class="hidden"></div>

  <div class="header-outer">
    <header class="guest-header">
      <div class="humbugger">
        <span class="material-icons" id="open-mobile-menu">menu</span>
      </div>
      <div class="logo">
        <%= link_to image_tag("5keeps.png", alt: "logo"), root_path %>
      </div>
      <%= render 'static_pages/search_form' %>
      <div class="links-guest">
        <div class="account">
          <span class="material-icons" id="account-icon">account_circle</span>
          <span class="user-name"><%= t "static_pages.guest.guest" %></span>
        </div>
        <%= link_to t("dictionary.common.signup"), signup_path, class: "button" %>
      </div>
    </header>
  </div class="header-outer">

  <main class="home-main">
    <%= render 'static_pages/home_menu_mobile' %>
    <%= render 'static_pages/home_menu_desktop' %>
    <%= render 'static_pages/edit_group_modal' %>
    <%= render 'static_pages/edit_link_modal' %>
    <section class="home-content">
      <%= render 'static_pages/add_group' %>
      <%= render 'static_pages/add_link' %>
      <ul class="link">
        <% if current_user.links.any? %>
          <%= render @links %>
        <% end %>
      </ul>
    </section>
    <div id="mask-mobile-menu" class="hidden">
      <span class="material-icons" id="close-mobile-menu">close</span>
    </div>
  </main>

  <%= render 'static_pages/footer' %>
</div><!-- /.home-container -->
<%= javascript_pack_tag 'custom/guest' %>

app/views/static_pages/home.html.erb
<% if logged_in? && !current_user.guest? %>
  <%= render 'static_pages/home_logged_in' %>
<% else %>
  <%= render 'static_pages/home_not_logged_in' %>
<% end %>

app/views/static_pages/home.js.erb
<%#■フラッシュを初期化  %>
document.getElementById('flash').innerHTML = '<%= j(render 'layouts/flash') %>';

<%#■現在のユーザーの全てのリンクを表示  %>
document.querySelector('.link').innerHTML = '<%= j(render @links) %>';

<%#■取得したリンクにイベントを追加   %>
<%#◉edit-iconをクリックした時のイベント %>
var editLinkIcons = document.querySelectorAll('.link .edit-icon');
var editLinkModal = document.getElementById('edit-link-modal');
var maskModal = document.getElementById('mask-modal');
<%# linkのedit-iconをクリック %>
editLinkIcons.forEach(icon => {
  icon.addEventListener('click', () => {
    // editLinkModal/ maskModalの表示
    editLinkModal.classList.remove('hidden');
    maskModal.classList.remove('hidden');

    // クリックされたedit-iconのdata-id, data-titleを取得
    var id = icon.dataset.id;
    var title = icon.dataset.title;
    var url = icon.dataset.url;

    // editLinkModalのURLに代入する (Update用)
    editLinkModal.setAttribute('action', `links/${id}`);

    // delete-iconのURLに代入する (Delete用)
    var deleteIcon = document.querySelector('#edit-link-modal .delete-icon');
    deleteIcon.setAttribute('href', `links/${id}`);

    // editLinkModalの中身にtitleとurlに代入する
    document.querySelector('#edit-link-modal #link_title').value = title;
    document.querySelector('#edit-link-modal #link_url').value = url;
  });
});