config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|ja/ do
    root 'static_pages#home'

    # static_pages
    get '/guest', to:'static_pages#guest'
    get '/terms', to:'static_pages#terms'
    get '/privacy', to:'static_pages#privacy'

    # users
    get '/signup', to:'users#new'
    post '/guest', to:'users#create_guest'
    resources :users, only: [:new, :create, :edit, :update, :destroy]

    # sessions
    get     '/login', to:'sessions#new'
    post   '/login', to:'sessions#create'
    delete '/logout', to:'sessions#destroy'

    # account_activations
    resources :account_activations, only: [:edit]

    # password_resets
    resources :password_resets, only: [:new, :create, :edit, :update]

    # contacts
    resources :contacts, only: [:new, :create]

    # link_groups
    resources :link_groups, only: [:show, :create, :update, :destroy]

    # links
    resources :links, only: [:create, :update, :destroy]
    get '/search', to:'links#search'
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = t('.flash.info')
      redirect_to root_url
    else
      flash.now[:danger] = t('.flash.danger')
      render 'new'
    end
  end

  def edit
  end

  def update
    # バリデーション(未入力: モデルではallow nil)
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update(user_params)
      log_in @user
      # 再設定済み => 再設定用リンクを使用不可にする
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = t('.flash.success')
      redirect_to root_url
    else
      # 更新に失敗 => エラーメッセージ(未入力以外)
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # editとupdateで必要な@userの取得をまとめて行う
    def get_user
      @user = User.find_by(email: params[:email])
    end

    # 正しいユーザーかどうか確認
    def valid_user
      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # リセットトークンの期限切れを確認
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = t('password_resets.check_expiration.flash.danger')
        redirect_to new_password_reset_url
      end
    end
end

app/views/password_resets/edit.html.erb
<% provide(:title, t('.title')) %>
<div class="form-container">
  <section class="logo form">
    <%= link_to image_tag("5keeps.png", alt: "logo"), root_path %>
  </section>

  <section class="form-main">
    <h1><%= t('.h1') %></h1>
      <%= render 'shared/error_messages' %>
    <%= form_with(model: @user,
                            url: password_reset_path(params[:id]),
                            local: true,
                            class: "user-form") do |f| %>
      <%= hidden_field_tag :email, @user.email %>
      <div>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control'  %>
      </div>
      <div>
        <%= f.label :password_confirmation, User.human_attribute_name(:password_confirmation) %>
        <%= f.password_field :password_confirmation, class: 'form-control'  %>
      </div>
      <%= f.submit t('.button'), class: "button" %>
    <% end %>
  </section>

  <%= render 'static_pages/footer' %>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, t('.title')) %>
<div class="form-container">
  <section class="logo form">
    <%= link_to image_tag("5keeps.png", alt: "logo"), root_path %>
  </section>

  <section class="form-main">
    <h1><%= t('.h1') %></h1>
    <%= form_with(url: password_resets_path, scope: :password_reset, local: true, class: "user-form") do |f| %>
      <div>
        <%= f.label :email, t('helpers.label.email') %>
        <%= f.email_field :email, class: 'form-control'  %>
      </div>
      <%= f.submit t('.button'), class: "button" %>
    <% end %>
  </section>

  <%= render 'static_pages/footer' %>
</div>